'use strict';
const $=id=>document.getElementById(id);let catalog,selected,frame=0,filter='all',csrf='',allJobs=[];
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,6000);}
async function api(path,body){if(body){const auth=await fetch('/api/catalog',{cache:'no-store'});if(!auth.ok)throw Error('The local server is unavailable');csrf=(await auth.json()).csrf;}const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-IsaacMin-Token':csrf},body:JSON.stringify(body)}:{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function image(id,entry){const element=$(id);element.hidden=!entry;if(entry){element.src=entry.url;element.alt=entry.caption;}else element.removeAttribute('src');}
function choose(ident){selected=catalog.presets.find(p=>p.id===ident)||catalog.presets[0];frame=0;filter='all';localStorage.setItem('isaacmin-preset',selected.id);history.replaceState(null,'','/library?preset='+selected.id);render();}
function renderConversation(){
 const conversation=$('conversation'),previous=conversation.scrollTop,follow=conversation.scrollHeight-previous-conversation.clientHeight<60;
 $('conversation').replaceChildren();
 for(const job of [...allJobs].reverse().filter(j=>j.action==='agent'&&j.preset===selected?.id)){
  if(job.prompt)$('conversation').append(node('div','chat user',job.prompt));
  const text=job.result?.answer||job.error||(job.status==='running'?'Inspecting your request…':job.status==='queued'?'Request saved; waiting for the worker.':null);
  if(text)$('conversation').append(node('div','chat',text));
 }
 conversation.scrollTop=follow?conversation.scrollHeight:previous;
}
function render(){
 const hasBuiltins=catalog.presets.some(p=>p.isaac.length);
 $('empty-library').hidden=hasBuiltins||allJobs.some(j=>j.action==='convert'&&j.status==='complete');
 $('presets').hidden=!hasBuiltins;document.querySelector('.workspace').hidden=!hasBuiltins;$('agent-toggle').hidden=!hasBuiltins;
 const p=selected;$('view-controls').dataset.preset=p.id;$('presets').replaceChildren();catalog.presets.forEach((preset,index)=>{const b=node('button','preset'+(preset.id===p.id?' selected':''));b.setAttribute('aria-pressed',String(preset.id===p.id));const im=node('img');im.src=preset.isaac[0]?.url||'';im.alt='';b.append(im);const label=node('span');label.append(node('strong','',preset.title),node('small','',preset.subtitle));b.append(label);b.onclick=()=>choose(preset.id);$('presets').append(b);});
 $('world-title').textContent=p.title;$('world-category').textContent=`WORLD ${String(catalog.presets.indexOf(p)+1).padStart(2,'0')} / ${p.id.toUpperCase()}`;$('extent').textContent=`${p.extent_m.join(' × ')} m region`;$('coordinates').textContent=`X ${p.center[0].toFixed(1)} · Z ${p.center[1].toFixed(1)}`;$('qualification').textContent=p.qualification;
 const source=p.minecraft[0];image('source-image',source);$('source-empty').hidden=!!source;$('source-caption').textContent=source?'Source-save aerial · Chunky':'';$('source-expand').hidden=!source;
 if(frame>=p.isaac.length)frame=0;const current=p.isaac[frame];image('isaac-image',current);$('isaac-empty').hidden=!!current;$('isaac-caption').textContent=current?.caption||'';$('isaac-expand').hidden=!current;
 $('thumbnails').replaceChildren();p.isaac.forEach((entry,index)=>{if(filter!=='all'&&filter!==entry.kind)return;const button=node('button','thumbnail'+(index===frame?' selected':''));button.setAttribute('aria-label',entry.caption);button.setAttribute('aria-pressed',String(index===frame));const im=node('img');im.src=entry.url;im.alt='';im.loading='lazy';button.append(im,node('span','',entry.caption));button.onclick=()=>{frame=index;render();};$('thumbnails').append(button);});
 document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('selected',b.dataset.filter===filter));
 $('download').hidden=!p.download;$('prepare').hidden=!!p.download;if(p.download){$('download').href=p.download.url;$('delivery-description').textContent=`Portable USD, original materials and assets · ${(p.download.bytes/1e9).toFixed(1)} GB ZIP`;}else $('delivery-description').textContent='Portable USD, materials and assets. Open locally in Isaac Sim.';
 $('planner-status').textContent=catalog.planner.status==='available'?`Ready · ${catalog.planner.model.split('/').pop()}`:`Planner unavailable · ${catalog.planner.reason}`;$('agent-send').disabled=catalog.planner.status!=='available';
 $('assistant-world').textContent='Selected world · '+p.title;renderConversation();
}
async function submit(action,prompt=''){const button=action==='agent'?$('agent-send'):$(action);if(button)button.disabled=true;try{const result=await api('/api/jobs',{preset:selected.id,action,prompt,operation_key:crypto.randomUUID()});toast('Request saved. Follow its progress below.');await pollJobs();return result;}catch(e){toast(e.message);}finally{if(button)button.disabled=action==='agent'&&catalog.planner.status!=='available';}}
async function pollJobs(){try{const data=await api('/api/jobs');allJobs=data.jobs;$('empty-library').hidden=catalog.presets.some(p=>p.isaac.length>0)||allJobs.some(j=>j.action==='convert'&&j.status==='complete');$('connection').textContent=Object.values(data.workers||{}).includes('stopped')?'Workers stopped · saved views available':'Local workspace';$('jobs').replaceChildren();if(!data.jobs.length)$('jobs').append(node('p','subtle','No saved work. Start from a Minecraft preset.'));for(const job of data.jobs){const row=node('div','job');row.dataset.jobId=job.id;const main=node('div','job-main');const preset=catalog?.presets.find(p=>p.id===job.preset);main.append(node('div','job-title',`${preset?.title||job.preset} · ${{verify:'File verification',prepare:'World download',convert:'New conversion',views:'Additional views',agent:'Assistant request'}[job.action]}`),node('div','job-detail',job.error||job.progress||job.result?.message||({queued:'Waiting for the local worker.',running:'Working. This job is saved if the page closes.',complete:'Completed.',interrupted:'Interrupted. Resume continues from retained work.',cancelled:'Cancelled before execution. Saved work is preserved.'}[job.status]||'')));row.append(main,node('span','badge '+job.status,job.status));if(job.action==='convert'&&job.status!=='complete'){const build=node('a','quiet','Watch build ↗');build.href='/?job='+job.id;row.append(build);}if(job.view_url){const view=node('a','quiet','View result ↗');view.href=job.view_url;row.append(view);}if(job.download_url){const download=node('a','quiet','Download ↓');download.href=job.download_url;row.append(download);}if(['failed','interrupted','cancelled'].includes(job.status)&&job.attempts<3){const resume=node('button','quiet','Resume');resume.onclick=async()=>{try{await api('/api/jobs/resume',{id:job.id,operation_key:crypto.randomUUID()});pollJobs();}catch(e){toast(e.message);}};row.append(resume);}if(job.status==='queued'){const cancel=node('button','quiet','Cancel');cancel.onclick=async()=>{cancel.disabled=true;try{await api('/api/jobs/cancel',{id:job.id,operation_key:crypto.randomUUID()});await pollJobs();}catch(e){toast(e.message);cancel.disabled=false;}};row.append(cancel);}$('jobs').append(row);}renderConversation();
 }catch(e){$('connection').textContent='Reconnecting…';}}
async function reload(){const fresh=await api('/api/catalog');csrf=fresh.csrf;const oldId=selected?.id||new URLSearchParams(location.search).get('preset');catalog=fresh;selected=fresh.presets.find(p=>p.id===oldId)||fresh.presets.find(p=>p.id===localStorage.getItem('isaacmin-preset'))||fresh.presets[0];render();}
function enlarge(which){const im=$(which+'-image');if(!im.hidden){$('lightbox-image').src=im.src;$('lightbox-image').alt=im.alt;$('lightbox-caption').textContent=$(which+'-caption').textContent;$('lightbox').showModal();}}
$('agent-toggle').onclick=()=>{$('assistant').hidden=false;$('prompt').focus();};$('agent-close').onclick=()=>$('assistant').hidden=true;$('source-expand').onclick=()=>enlarge('source');$('isaac-expand').onclick=()=>enlarge('isaac');$('lightbox-close').onclick=()=>$('lightbox').close();$('lightbox').onclick=e=>{if(e.target===$('lightbox'))$('lightbox').close();};$('verify').onclick=()=>submit('verify');$('prepare').onclick=()=>submit('prepare');
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;const first=selected.isaac.findIndex(i=>filter==='all'||i.kind===filter);if(first>=0)frame=first;render();});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.prompt;$('prompt').focus();});
$('agent-form').onsubmit=async e=>{e.preventDefault();const text=$('prompt').value.trim();if(!text)return;const result=await submit('agent',text);if(result)$('prompt').value='';};
reload().then(pollJobs).catch(e=>toast('Could not load workspace: '+e.message));setInterval(pollJobs,3000);setInterval(()=>reload().catch(()=>{}),15000);

document.addEventListener('isaacmin:views-queued',pollJobs);document.addEventListener('isaacmin:views-ready',()=>reload().then(pollJobs));
